config/routes.rb
Rails.application.routes.draw do
	root to: 'articles#index'
	resources :articles do
		resources :comments
	end
	resources :tags
	resources :authors
	resources :author_sessions, only: [ :new, :create, :destroy ]
	resources :search
	
	get 'login' => 'author_sessions#new'
	get 'logout' => 'author_sessions#destroy'
	get '/show' => 'search#show'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
	has_many :comments, dependent: :delete_all
	has_many :taggings
	has_many :tags, through: :taggings
	has_one :search
	has_attached_file :image
	validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/jpeg"]
	is_impressionable

	def tag_list
		tags.join(", ")
	end

	def tag_list=(tags_string)
		tag_names = tags_string.split(",").collect{|s| s.strip.downcase}.uniq
		new_or_found_tags = tag_names.collect{ |name| Tag.find_or_create_by(name: name) }
		self.tags = new_or_found_tags
	end
end

app/models/author.rb
class Author < ApplicationRecord
  authenticates_with_sorcery!
  validates_confirmation_of :password, message: "should match confirmation", if: :password
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
end

app/models/search.rb
class Search < ApplicationRecord
	has_many :articles

	def article_list

	end
end

app/models/tag.rb
class Tag < ApplicationRecord
	has_many :taggings
	has_many :articles, through: :taggings, dependent: :destroy

	def to_s
		name
	end
end

app/models/tagging.rb
class Tagging < ApplicationRecord
  belongs_to :tag
  belongs_to :article
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	include ArticlesHelper
	impressionist actions: [:show]
	before_action :require_login, except: [:index, :show]
	def index
		@articles = Article.all
	end

	def show
		@article = Article.find(params[:id])
		@comment = Comment.new
		@comment.article_id = @article.id
	end

	def new
		@article = Article.new
	end

	def create
		@article = Article.new(article_params)
		@article.save

		flash.notice = "Created Article, Titled: '#{@article.title}'"
		redirect_to article_path(@article)
	end

	def destroy
		@article = Article.destroy(params[:id])

		flash.notice = "Article Deleted."
		redirect_to articles_path
	end

	def edit
		@article = Article.find(params[:id])
	end

	def update
		@article = Article.find(params[:id])
		@article.update(article_params)

		flash.notice = "Article '#{@article.title}' Updated!"
		redirect_to article_path(@article)
	end
end

app/controllers/author_sessions_controller.rb
class AuthorSessionsController < ApplicationController
	def new
	end

	def create
		if login(params[:email], params[:password])
			redirect_back_or_to(articles_path, notice: 'Logged in Successfully!')
		else
			flash.now.alert = "Login failed."
			render action: :new
		end
	end

	def destroy
		logout
		redirect_to(:authors, notice: 'Logged out!')
	end
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :set_author, only: [:show, :edit, :update, :destroy]
  before_action :require_login, except: [:new, :create]

  # GET /authors
  # GET /authors.json
  def index
    @authors = Author.all
  end

  # GET /authors/1
  # GET /authors/1.json
  def show
  end

  # GET /authors/new

  before_action :zero_authors_or_authenticated, only: [:new, :create]


  def zero_authors_or_authenticated
    unless Author.count == 0 || current_user
      redirect_to root_path
      return false
    end
  end

  def new
    @author = Author.new
  end

  # GET /authors/1/edit
  def edit
  end

  # POST /authors
  # POST /authors.json
  def create
    @author = Author.new(author_params)

    respond_to do |format|
      if @author.save
        format.html { redirect_to @author, notice: 'Author was successfully created.' }
        format.json { render :show, status: :created, location: @author }
      else
        format.html { render :new }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /authors/1
  # PATCH/PUT /authors/1.json
  def update
    respond_to do |format|
      if @author.update(author_params)
        format.html { redirect_to @author, notice: 'Author was successfully updated.' }
        format.json { render :show, status: :ok, location: @author }
      else
        format.html { render :edit }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /authors/1
  # DELETE /authors/1.json
  def destroy
    @author.destroy
    respond_to do |format|
      format.html { redirect_to authors_url, notice: 'Author was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_author
      @author = Author.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def author_params
      params.require(:author).permit(:username, :email, :password, :password_confirmation)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_action :require_login, except: [:create]
	def create
		@comment = Comment.new(comment_params)
		@comment.article_id = params[:article_id]
		@comment.save

		redirect_to article_path(@comment.article)
	end

	def comment_params
		params.require(:comment).permit(:author_name, :body)
	end

end

app/controllers/search_controller.rb
class SearchController < ApplicationController

	def show
		@year = params["year"]
		@month = params["month"]
		articles = Article.all
		@relevant_articles = []

		articles.each do |article|
			if(@year == article.created_at.to_s[0..3]) &&
				(@month[0..1] == article.created_at.to_s[5..6])
					@relevant_articles << article
			end
		end
	end

	def index
		articles = Article.all
		@publishing_date = {}
		articles.each do |article|
			@publishing_date[article.id] = [article.created_at.to_s[0..3],
											article.created_at.to_s[5..6]]
		end
	end

	def create
		@search = Search.new
		redirect_to search_path(:show)
	end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
	before_action :require_login, only: [:destroy]
	def show
		@tag = Tag.find(params[:id])
	end

	def index
		@tags = Tag.all
	end

	def destroy
		@tag = Tag.find(params[:id]).destroy

		flash.notice = "Tag: '#{@tag.to_s}' Removed"
		redirect_to tags_path
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
	def article_params
		params.require(:article).permit(:title, :body, :tag_list, :image)
	end
end

app/helpers/author_sessions_helper.rb
module AuthorSessionsHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/articles/_comment.html.erb
<div>
	<h4>Comment by <%= comment.author_name %></h4>
	<p class="comment"><%= comment.body %></p>
	<p>Posted <%= distance_of_time_in_words(comment.article.created_at, comment.created_at) %> later</p>
</div>

app/views/articles/_form.html.erb
<%= form_for(@article, html: {multipart: true}) do |f| %>
	<ul>
	<% @article.errors.full_messages.each do |error| %>
		<li><%= error %></li>
	<% end %>
	</ul>
	<p>
		<%= f.label :title %><br />
		<%= f.text_field :title %>
	</p>
	<p>
		<%= f.label :body %> <br />
		<%= f.text_area :body%>
	</p>
	<p>
		<%= f.label :tag_list %><br />
		<%= f.text_field :tag_list %>
	</p>
	<p>
		<% if @article.image.exists? %>
			<%= image_tag @article.image.url %><br/>
		<% end %>
		<%= f.label :image, "Attach a new Image" %><br />
		<%= f.file_field :image %>
	</p>
	<p>
		<%= f.submit %>
	</p>
<% end %>

app/views/articles/_navbar.html.erb
<ul class="navbar_list" id = "popular_list">
 	<%  article_list = {}
    	Article.all.each do |article|
              article_list[article.impressionist_count] = article
        end
        top_list = article_list.keys.sort.reverse[0..2]
        top_list.each do |key| %>
        <li class ="nav_item">
        	<%= link_to article_list[key].title, article_path(article_list[key]) %>
        </li>
    <% end %>
</ul>

app/views/articles/edit.html.erb
<h1>Edit an Article</h1>
<%= render partial: 'form' %>

app/views/articles/index.html.erb
<h1>All Articles</h1>

<div id = "articles_container">
	<ul id = "articles">
		<% @articles.each do |article|%>
			<li>
				<%= link_to article.title, article_path(article) %>
			</li>
		<% end %>
		<br />
		<% if logged_in? %>
			<strong><%= link_to "Create a New Article", new_article_path, class: 'article_title' %></strong><br /><br />
		<% end %>
		<i><%= link_to "List of Article Tags", tags_path %></i>
	</ul>
</div>

app/views/articles/new.html.erb
<h1>Create a New Article</h1>
<%= render partial: 'form' %>

app/views/articles/show.html.erb
<h1><%= @article.title %></h1>
<h3 class="article_timestamp" id ="posted_at">
	<i>Originally posted on: </i>
	<%= "#{@article.created_at.to_s}" %>
</h3>
<% if @article.created_at != @article.updated_at %>
	<h3 class="article_timestamp" id ="updated_at">
		<i>Last updated: </i>
		<%= "#{@article.updated_at.to_s}" %>
	</h3>
<% end %>
<p>
	<strong>Tags:</strong>
	<% @article.tags.each do |tag| %>
		<%= link_to tag.name, tag_path(tag) %>
	<% end %>
</p>
	<% if @article.image.exists? %>
		<p><%= image_tag @article.image.url %>
	<% end %>
</p>
<p><%= @article.body %></p>
<p id="view_count"><%= "#{@article.impressionist_count} View(s)" %>
<h4 class="comment_title"><strong>Comments</strong> (<%= @article.comments.size %>)</h3>
	<%= render partial: 'articles/comment', collection: @article.comments %>
<%= render partial: 'comments/form' %>
<span class = "search_result_link">
<%= link_to "<< Back to Articles List", articles_path %>
</span>
<% if logged_in? %>
	<%= link_to "edit", edit_article_path(@article) %>
	<%= link_to "delete", article_path(@article), data: {confirm: "Really delete the article?"}, method: :delete%>
<% end %>

app/views/author_sessions/_navbar.html.erb
<ul class="navbar_list" id = "popular_list">
 	<%  article_list = {}
    	Article.all.each do |article|
              article_list[article.impressionist_count] = article
        end
        top_list = article_list.keys.sort.reverse[0..2]
        top_list.each do |key| %>
        <li class ="nav_item">
        	<%= link_to article_list[key].title, article_path(article_list[key]) %>
        </li>
    <% end %>
</ul>

app/views/author_sessions/new.html.erb
<h1>Login</h1>

<%= form_tag author_sessions_path, method: :post do %>
	<div class="field">
		<%= label_tag :email %>
		<%= text_field_tag :email %>
		<br/>
	</div>
	<div class="field">
		<%= label_tag :password %>
		<%= password_field_tag :password %>
		<br/>
	</div>
	<div class="actions">
		<%= submit_tag "Login" %>
	</div>
<% end %>

app/views/authors/_form.html.erb
<%= form_with(model: author, local: true) do |form| %>
  <% if author.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(author.errors.count, "error") %> prohibited this author from being saved:</h2>

      <ul>
      <% author.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :username %>
    <%= form.text_field :username %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :password %><br />
    <%= form.password_field :password %>
  </div>

  <div class="field">
    <%= form.label :password_confirmation %><br />
    <%= form.password_field :password_confirmation %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/authors/_navbar.html.erb
<ul class="navbar_list" id = "popular_list">
 	<%  article_list = {}
    	Article.all.each do |article|
              article_list[article.impressionist_count] = article
        end
        top_list = article_list.keys.sort.reverse[0..2]
        top_list.each do |key| %>
        <li class ="nav_item">
        	<%= link_to article_list[key].title, article_path(article_list[key]) %>
        </li>
    <% end %>
</ul>

app/views/authors/edit.html.erb
<h1>Editing Author</h1>

<%= render 'form', author: @author %>

<%= link_to 'Show', @author %> |
<%= link_to 'Back', authors_path %>

app/views/authors/index.html.erb
<h1>Authors</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @authors.each do |author| %>
      <tr>
        <td><%= author.username %></td>
        <td><%= author.email %></td>
        <td><%= link_to 'Show', author %></td>
        <td><%= link_to 'Edit', edit_author_path(author) %></td>
        <td><%= link_to 'Destroy', author, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Author', new_author_path %>

app/views/authors/new.html.erb
<h1>New Author</h1>

<%= render 'form', author: @author %>

<%= link_to 'Back', authors_path %>

app/views/authors/show.html.erb
<p>
  <strong>Username:</strong>
  <%= @author.username %>
</p>

<p>
  <strong>Email:</strong>
  <%= @author.email %>
</p>

<%= link_to 'Edit', edit_author_path(@author) %> |
<%= link_to 'Back', authors_path %>

app/views/comments/_form.html.erb
<h4 class="comment_title"><i>Post a Comment</i></h3>

<%= form_for [ @article, @comment ] do |f| %>
	<p class = "comment_label">
		<%= f.label :author_name, "Your Name -" %><br/>
		<%= f.text_field :author_name, :required =>true, :class =>"comment_text", :id => "comment_author", :maxlength => 20 %>
	</p>
	<p class = "comment_label">
		<%= f.label :body, "Your Comment (500 char. limit) -" %><br />
		<%= f.text_area :body, :required => true, :class =>"comment_text", :id => "comment_field", :maxlength => 500 %>
	</p>
		<%= f.submit 'Submit'%>
	</p>
<% end %>

app/views/search/_form.html.erb
	<%= form_tag("/show", method: 'get') do %>
		<% months = ['01 - Jan', '02 - Feb', '03 - Mar', '04 - Apr', '05 - May', '06 - Jun', '07 - Jul', '08 - Aug', '09 - Sept', '10 - Oct', '11 - Nov', '12 - Dec'] %>
		<% years = ['2016', '2017', '2018'] %>
		<%= label_tag 'Select Month:' %><br/>
		<%= select_tag('month', options_for_select(months, 'Jan'), {:class => 'navbar_select_field'}) %><br/>
		<%= label_tag 'Select Year:' %><br/>
		<%= select_tag('year', options_for_select(years, '2018'), {:class => 'navbar_select_field'})%><br/>
		<%= submit_tag("search", {:id => 'navbar_submit_button'}) %>
	<% end %>

app/views/search/_navbar.html.erb
<ul class="navbar_list" id = "popular_list">
 	<%  article_list = {}
    	Article.all.each do |article|
              article_list[article.impressionist_count] = article
        end
        top_list = article_list.keys.sort.reverse[0..2]
        top_list.each do |key| %>
        <li class ="nav_item">
        	<%= link_to article_list[key].title, article_path(article_list[key]) %>
        </li>
    <% end %>
</ul>

app/views/search/index.html.erb
<h1>Search</h1>
<p id="search_home">
		<%= form_tag("/show", method: 'get') do %>
		<% months = ['01 - Jan', '02 - Feb', '03 - Mar', '04 - Apr', '05 - May', '06 - Jun', '07 - Jul', '08 - Aug', '09 - Sept', '10 - Oct', '11 - Nov', '12 - Dec'] %>
		<% years = ['2016', '2017', '2018'] %>
		<%= label_tag 'Select Month:', nil, class: 'search_home_field_label'  %><br/>
		<%= select_tag('month', options_for_select(months, 'Jan'), {:class => 'search_home_select_field'}) %><br/>
		<%= label_tag 'Select Year:', nil, class: 'search_home_field_label' %><br/>
		<%= select_tag('year', options_for_select(years, '2018'), {:class => 'search_home_select_field'})%><br/>
		<%= submit_tag("search", {:id => 'search_home_submit_button'}) %>
	<% end %>
</p>

app/views/search/show.html.erb
<h1>Search</h1>
<h3>Showing articles published in <%= @month[5..8] %> <%= @year %>:</h3>
<div>
	<% if @relevant_articles.length == 0 %>
		No articles published in that time frame - try a different search.<br/><br/>
		<%= link_to "<< Search Home", search_index_path %>
	<% else %>
		<% @relevant_articles.each do |article| %>
		<p class ="search_result_link">
			<%= link_to article.title, article_path(article)%>
		</p>
		<% end %>
		<span class ="search_result_link">
			<%= link_to "<< Search Home", search_index_path %>
		</span>
	<% end %>
</div>

app/views/tags/_navbar.html.erb
<ul class="navbar_list" id = "popular_list">
 	<%  article_list = {}
    	Article.all.each do |article|
              article_list[article.impressionist_count] = article
        end
        top_list = article_list.keys.sort.reverse[0..2]
        top_list.each do |key| %>
        <li class ="nav_item">
        	<%= link_to article_list[key].title, article_path(article_list[key]) %>
        </li>
    <% end %>
</ul>

app/views/tags/index.html.erb
<h1>Tag List</h1>
<p class = "all_tags_body">
	Tags:<br/><br/>
	<% @tags.each do |tag| %>
		<span class = "search_result_link">
			<strong><%= link_to tag.name, tag_path(tag) %></strong>
		</span>
		<% if logged_in? %>
			<%= link_to "delete tag", tag_path(tag), method: :delete, data: {confirm: "Delete this tag?"}%>
		<% end %>
		<br/>
	<% end %>
</p>
<p id = "all_articles_link">
	<span class = "search_result_link">
		<%= link_to "All Articles >>", articles_path %>
	</span>
</p>

app/views/tags/show.html.erb
<h1>Articles Tagged with <%= @tag.name %></h1>

<ul>
	<% @tag.articles.each do |article| %>
		<li><%= link_to article.title, article_path(article) %></li>
	<% end %>
</ul>